#!/usr/bin/perl -w
use strict;

# $Id: runner,v 1.1 2008-08-08 11:32:11 roderick Exp $

use lib '/usr/local/src/zavandor/lib';

$ENV{TERM} ||= 'vt100';

require Game::ScepterOfZavandor::Game;
Game::ScepterOfZavandor::Game::run_game();
