#!/usr/bin/perl -w
use strict;

# $Id: runner,v 1.3 2012-09-14 01:16:51 roderick Exp $

use FindBin qw($Bin);
use lib "$Bin/lib";

$ENV{TERM} //= 'vt100';

require Game::ScepterOfZavandor::Game;

# XXX eval, somehow log errors if it fails

Game::ScepterOfZavandor::Game::run_game();
